[project]
name = "pythontest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.11.0",
    "fastmcp>=2.13.0.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.19.0",
]
